### PR TITLE
Make the Sentry handler safer dealing with unknown values

### LINKED ISSUE #644: Adding a string with the key `user` to loging context throws an exception
### Environment

Sentry: 3.1.3
Laravel: 9.43.0

### Steps to Reproduce

1. Use sentry as the logger driver

```
        'stack' => [
            'driver' => 'stack',
            'channels' => ['daily', 'sentry'],
            'ignore_exceptions' => false,
        ],
```

2. Send a log

```
logger()->info('user', ['userId' => 5, 'user' => 'abc'])
```

### Expected Result

The log is added without any problems.

If this is expected behaviour, this should be explicitly documented somewhere

### Actual Result

An exception is thrown, b/c `user` is apparently a reserved keyword, and passing it in the log creates an exception

image

### PR DESCRIPTION
**Pull request by stayallive**
I've added a bunch of checks and try to err on the side of caution where we might not set values on the scope but try to always get the event out the door instead of crashing.

Also added a few tests, long way from exhaustive but better than before.

Fixes #644.

### CODE REVIEW

File: src/Sentry/Laravel/SentryHandler.php [hunk 1]
```diff
@@ -301,4 +291,65 @@ public function addBreadcrumb(Breadcrumb $crumb): self
...
+                unset($context['user']);
+            } catch (TypeError $e) {
+                // In some cases the context can be invalid, in that case we ignore it and
+                // choose to not send it to Sentry in favor of not breaking the application
+            }
+        }
+    }
+
+    /**
+     * Test if the value passed can be casted to a string.
```
Comment (cleptric) [inline src/Sentry/Laravel/SentryHandler.php:345]:
```suggestion
     * Check if the value passed can be cast to a string.
```

**Review by cleptric — APPROVED** [review]
